
spring.datasource.url=jdbc:mysql://localhost:3306/hotel_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=40409179

# JPA/Hibernate ??
# update ?????? Java ???????????

spring.jpa.hibernate.ddl-auto=update

spring.sql.init.mode=always

spring.jpa.show-sql=true
# ?????? SQL
spring.jpa.properties.hibernate.format_sql=true
# ???????
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
server.port=8089