# ===================================================================
# Spring ????
# ===================================================================
server.port=8089
spring.application.name=hotel-booking
# ?? Spring AI M1 ??? Spring Boot ?? Bean ???????????
spring.main.allow-bean-definition-overriding=true

# ===================================================================
# ????? (H2 ? MySQL?????????????)
# ===================================================================
spring.datasource.url=jdbc:mysql://localhost:3306/hotel_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=40409179
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ?? API ????? OpenAI ???
# ??? api-key ?????????
spring.ai.openai.api-key=d9ad65bd-d578-48e5-973a-afc7fd4eb081
# ??? base-url ????????

# ??? model ?????????? ID???? ep-2024xxxxxxxx
spring.ai.openai.chat.options.model=ep-20260319181528-8xkbb

spring.ai.openai.embedding.options.model=ep-20260319181801-sbvrt

logging.level.org.springframework.ai=DEBUG
logging.level.org.springframework.web.client.RestClient=DEBUG